Default pr list to open prs
pwntester/octo.nvim pull request #134
Opened 2021-03-18 18:00 UTC by jpribyl

### Describe what this PR does / why we need it
Problem: In a production environment, it's common to have 1000s of PRs and unless I use a browser, I'm not going to know what is currently open and what is not. It's tedious to always type `Octo pr list states=OPEN`

Solution: default the state argument to "OPEN" - this matches the behavior of the gh-cli's `gh pr list` https://cli.github.com/manual/gh_pr_list

### Does this pull request fix one issue?

NONE

### Describe how you did it
Added a default for `opts.states` in `menu.pull_requests`

### Describe how to verify it

1. Open vim
2. Run `Octo pr list` to verify that open works
3. Run `Octo pr list states=CLOSED` to verify that closed works
4. Run `Octo pr list states=MERGED` to verify that merged works

### Special notes for reviews

2021-03-18 20:24 UTC, pwntester requested changes
Thanks! It makes sense but can you please add a similar default for issues?

2021-03-19 22:36 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"ALL"', "ALL")
test

comment at commit level (line 62) that will be deleted in commit afterwards

2021-03-19 22:37 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"MERGED"', "MERGED")
this comment should not be deleted

2021-03-20 15:06 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"ALL"', "ALL")
test

2021-03-20 15:07 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"MERGED"', "MERGED")
test1

2021-03-20 15:08 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"MERGED"', "MERGED")
test1

2021-03-20 15:08 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"ALL"', "ALL")
test2

2021-03-20 15:10 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"ALL"', "ALL")
test2

2021-03-20 15:12 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"ALL"', "ALL")
'test1'

2021-03-20 15:13 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"ALL"', "ALL")
test1
test2

2021-03-20 15:13 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"MERGED"', "MERGED")
test

2021-03-20 15:14 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"MERGED"', "MERGED")
test1
test2

2021-03-20 15:16 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"MERGED"', "MERGED")
test1
test2

2021-03-20 21:54 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"ALL"', "ALL")
test2

2021-03-20 21:54 UTC, pwntester commented on lua/octo/menu.lua
> +      val = string.gsub(val, '"MERGED"', "MERGED")
test2

2021-03-20 21:56 UTC, pwntester commented on lua/octo/menu.lua
>        val = string.gsub(val, '"CLOSED"', "CLOSED")
test2

2021-03-20 22:24 UTC, merged

2021-03-20 22:24 UTC, pwntester commented
Thanks!

2021-03-21 17:38 UTC, jpribyl commented
@pwntester oops, I didn't quite get around to adding a similar default for issues! I will open another PR

2021-03-21 17:39 UTC, jpribyl commented
nvm, looks like you did it :+1: thanks for taking care of that!

2021-03-21 18:43 UTC, pwntester commented
No problem, thanks for the PR!